#config server
server:
  port: 80
  session-timeout: 30
#  servlet:
#    context-path: /clcs-server
#  jetty:
#    max-http-form-post-size: 121251215421


#config custom info
upload-path: /static/upload/imgs/

spring:
  application:
    name: noendsys
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 36.103.243.107:8848
  #config devtools
  devtools:
    add-properties: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  #config alibaba druid
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://47.108.21.51:3306/noend?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: sunup
      password: shewWE6723&^23.
      #      url: jdbc:mysql://localhost:3306/noend?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      #      username: sunup
      #      password: sunup
      #      url: jdbc:mysql://localhost:3306/noend?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      #      username: lime
      #      password: lime
      # 连接池配置
      initial-size: 1
      min-idle: 1
      max-active: 5
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.sunup.noend.servie.*


      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true


  #config multipart file
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760
      enabled: true
  #config resources
  mvc:
    static-path-pattern: /static/**


    #redis
  #  redis:
  #    database: 0
  #    host: 36.103.240.26
  #    port: 6379
  #    password: 3b930f98f29b0a97b699dc027e3c81a9scoy123456!#$%wxd5c04a0b457efd8f
  #    jedis:
  #      pool:
  #        max-active: 8
  #        max-idle: 8
  #        min-idle: 0
  #        max-wait: -1
  #    timeout: 5000
  #email
  mail:
    host: smtp.qq.com
    username: 1933305628@qq.com
    password: tmjlywoprgzlfeic
    from: 1933305628@qq.com
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    debug: true
    default-encoding: utf-8
  #config log
logging:
  level:
    root: info
    web: debug
    com.sunup.noend.mapper: debug
  file: noendsys.log



